version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - api
    stdin_open: true
    tty: true
    links:
      - api
  api:
    image: checkr/flagr
    expose:
      - "18000"
    ports:
      - "18000:18000"
